---
- name: Create partition
  hosts: balancer
  tasks:
    - name: Checking disk space
      debug:
        msg: "this disk is not exist"
      when: "'sdb' not in ansible_devices"


    - name: Create primary partition
      block:
        - name: Create 1000M partition
          parted:
            device: /dev/sdb
            number: 1
            state: present
            part_end: 1000MiB
          when: "'sdb' in ansible_devices"
       
        - name: Update Information
          setup:
            filter: ansible_devices
    
      rescue: 
        - name: Checking disk space
          debug:
            msg: "this disk is not exist"
          when: "'sdb' in ansible_devices"
        
        - name: Create 500M partition
          parted:
            device: /dev/sdb
            number: 1
            state: present
            part_end: 500MiB
          when: "'sdb' in ansible_devices"

        - name: Update Information
          setup:
            filter: ansible_devices
    
      always:
        - name: Create filesystem
          filesystem:
            device: /dev/sdb1
            fstype: ext4
          when: "'sdb' in ansible_devices.sdb.partitions"

        - name: Create directory 
          file:
            path: /data
            state: directory
        
        - name: Create mount point
          mount: 
            src: /dev/sdb1
            path: /data
            fstype: ext4
            state: mounted
          when: "'prod' in group_names"